#!/usr/bin/env python3
"""
MT5 vs Python BollMR Signal Alignment Validator

Compares signals generated by MT5 EA with Python strategy implementation.
"""

import argparse
import sys
from pathlib import Path

import pandas as pd

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent))

from core.data import load_mt5_csv
from core.settings import load_settings
from strategies.boll_mean_reversion import BollMeanReversionStrategy, BollMeanReversionParams


def load_mt5_signals(filepath: str) -> pd.DataFrame:
    """Load MT5 exported signals file."""
    # MT5 exports with UTF-16 LE encoding with BOM
    df = pd.read_csv(filepath, sep="\t", encoding="utf-16-le")
    df["time"] = pd.to_datetime(df["time"])
    df = df.set_index("time")

    # signal is the sticky position state (0, 1, -1)
    df["signal"] = pd.to_numeric(df["signal"], errors="coerce").fillna(0).astype(int)

    # event is only populated when there's a new signal event
    # empty string means no event
    df["event"] = pd.to_numeric(df["event"], errors="coerce")
    # Keep NaN for no-event bars (don't fill with 0)
    # df["event"] = df["event"].fillna(0).astype(int)

    return df


def compare_signals(mt5_df: pd.DataFrame, py_events: pd.Series, py_state: pd.Series) -> dict:
    """Compare MT5 and Python signals bar by bar."""

    # Align indices
    common_idx = mt5_df.index.intersection(py_events.index)

    if len(common_idx) == 0:
        return {"error": "No common timestamps between MT5 and Python data"}

    mt5_aligned = mt5_df.loc[common_idx]
    py_events_aligned = py_events.loc[common_idx]
    py_state_aligned = py_state.loc[common_idx]

    # Count events - MT5 event is NaN when no event
    mt5_has_event = mt5_aligned["event"].notna()
    py_has_event = py_events_aligned.notna() & (py_events_aligned != 0)

    results = {
        "total_bars": len(common_idx),
        "mt5_signal_events": int(mt5_has_event.sum()),
        "py_signal_events": int(py_has_event.sum()),
    }

    # Count entries and exits
    mt5_events = mt5_aligned["event"].dropna()
    mt5_buy_entries = mt5_events[mt5_events == 1].index
    mt5_sell_entries = mt5_events[mt5_events == -1].index
    mt5_exits = mt5_events[mt5_events == 0].index

    py_events_valid = py_events_aligned.dropna()
    py_buy_entries = py_events_valid[py_events_valid == 1].index
    py_sell_entries = py_events_valid[py_events_valid == -1].index
    py_exits = py_events_valid[py_events_valid == 0].index

    results["mt5_buy_count"] = len(mt5_buy_entries)
    results["mt5_sell_count"] = len(mt5_sell_entries)
    results["mt5_exits"] = len(mt5_exits)
    results["py_buy_count"] = len(py_buy_entries)
    results["py_sell_count"] = len(py_sell_entries)
    results["py_exits"] = len(py_exits)

    # Check exact matches for entries
    buy_matches = set(mt5_buy_entries) & set(py_buy_entries)
    sell_matches = set(mt5_sell_entries) & set(py_sell_entries)

    results["buy_entry_matches"] = len(buy_matches)
    results["sell_entry_matches"] = len(sell_matches)

    # Missing in Python
    results["mt5_only_buy"] = [str(t) for t in (set(mt5_buy_entries) - set(py_buy_entries))]
    results["mt5_only_sell"] = [str(t) for t in (set(mt5_sell_entries) - set(py_sell_entries))]

    # Missing in MT5
    results["py_only_buy"] = [str(t) for t in (set(py_buy_entries) - set(mt5_buy_entries))]
    results["py_only_sell"] = [str(t) for t in (set(py_sell_entries) - set(mt5_sell_entries))]

    # State comparison (signal state should match)
    state_mismatches = []
    for idx in common_idx:
        mt5_state = mt5_aligned.loc[idx, "signal"]
        py_state_val = py_state_aligned.loc[idx]

        if mt5_state != py_state_val:
            state_mismatches.append({
                "time": idx,
                "mt5_state": mt5_state,
                "py_state": py_state_val,
            })

    results["state_mismatches"] = state_mismatches
    results["state_mismatch_count"] = len(state_mismatches)
    results["state_match_rate"] = (
        (results["total_bars"] - len(state_mismatches)) / results["total_bars"] * 100
        if results["total_bars"] > 0 else 0
    )

    # Event comparison (only when both have events)
    event_mismatches = []
    for idx in common_idx:
        mt5_event = mt5_aligned.loc[idx, "event"]
        py_event = py_events_aligned.loc[idx]

        # Skip if neither has an event
        if pd.isna(mt5_event) and (pd.isna(py_event) or py_event == 0):
            continue

        # Check if only one has an event
        if pd.isna(mt5_event) != pd.isna(py_event):
            event_mismatches.append({
                "time": idx,
                "mt5_state": mt5_aligned.loc[idx, "signal"],
                "mt5_event": mt5_event if not pd.isna(mt5_event) else "none",
                "py_event": py_event if not pd.isna(py_event) else "none",
                "py_state": py_state_aligned.loc[idx],
                "type": "one_sided",
            })
        elif mt5_event != py_event:
            event_mismatches.append({
                "time": idx,
                "mt5_state": mt5_aligned.loc[idx, "signal"],
                "mt5_event": mt5_event,
                "py_event": py_event,
                "py_state": py_state_aligned.loc[idx],
                "type": "value_mismatch",
            })

    results["event_mismatches"] = event_mismatches
    results["event_mismatch_count"] = len(event_mismatches)
    results["mismatches"] = event_mismatches  # For compatibility
    results["mismatch_count"] = len(event_mismatches)
    results["match_rate"] = results["state_match_rate"]  # Primary metric

    return results


def print_report(results: dict):
    """Print alignment report."""
    print("\n" + "=" * 60)
    print("MT5 vs Python Signal Alignment Report")
    print("=" * 60)

    print(f"\n[Overview]")
    print(f"  Total bars compared: {results['total_bars']}")

    print(f"\n[MT5 Signals]")
    print(f"  Buy entries: {results['mt5_buy_count']}")
    print(f"  Sell entries: {results['mt5_sell_count']}")
    print(f"  Exits: {results['mt5_exits']}")

    print(f"\n[Python Signals]")
    print(f"  Buy entries: {results['py_buy_count']}")
    print(f"  Sell entries: {results['py_sell_count']}")
    print(f"  Exits: {results['py_exits']}")

    print(f"\n[Entry Matches]")
    print(f"  Buy matches: {results['buy_entry_matches']}")
    print(f"  Sell matches: {results['sell_entry_matches']}")

    print(f"\n[State Alignment]")
    print(f"  State match rate: {results['state_match_rate']:.2f}%")
    print(f"  State mismatches: {results['state_mismatch_count']}")

    # Print discrepancies
    if results['mt5_only_buy']:
        print(f"\n[!] MT5 Buy (missing in Python): {results['mt5_only_buy'][:5]}")
    if results['mt5_only_sell']:
        print(f"[!] MT5 Sell (missing in Python): {results['mt5_only_sell'][:5]}")
    if results['py_only_buy']:
        print(f"[!] Python Buy (missing in MT5): {results['py_only_buy'][:5]}")
    if results['py_only_sell']:
        print(f"[!] Python Sell (missing in MT5): {results['py_only_sell'][:5]}")

    # Print first few event mismatches
    if results['event_mismatches']:
        print(f"\n[X] First 10 Event Mismatches:")
        for m in results['event_mismatches'][:10]:
            print(f"  {m['time']}: MT5(state={m['mt5_state']}, event={m['mt5_event']}) "
                  f"vs PY(state={m['py_state']}, event={m['py_event']}) [{m['type']}]")

    # Print first few state mismatches
    if results['state_mismatches'] and results['state_mismatch_count'] <= 20:
        print(f"\n[X] State Mismatches:")
        for m in results['state_mismatches'][:10]:
            print(f"  {m['time']}: MT5={m['mt5_state']} vs PY={m['py_state']}")

    print("\n" + "=" * 60)


def main():
    parser = argparse.ArgumentParser(description="Validate MT5 vs Python signal alignment")
    parser.add_argument(
        "--mt5-data",
        default="E:/mt5_test_datas/mt5/XAUUSD_M5_202601150100_202601302350.csv",
        help="Path to MT5 OHLCV data file",
    )
    parser.add_argument(
        "--mt5-signals",
        default="C:/Users/ruiwe/AppData/Roaming/MetaQuotes/Terminal/Common/Files/signals_mt5.csv",
        help="Path to MT5 exported signals file",
    )
    parser.add_argument(
        "--config",
        default="Python/config.json",
        help="Path to config file",
    )
    parser.add_argument(
        "--logic-mode",
        default="enhanced",
        choices=["base", "rsi", "time", "rsi_time", "enhanced"],
        help="Strategy logic mode",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="Enable debug output",
    )
    args = parser.parse_args()

    print(f"Loading MT5 OHLCV data from: {args.mt5_data}")
    ohlcv_df = load_mt5_csv(args.mt5_data)
    print(f"  Loaded {len(ohlcv_df)} bars")

    print(f"\nLoading MT5 signals from: {args.mt5_signals}")
    mt5_signals = load_mt5_signals(args.mt5_signals)
    print(f"  Loaded {len(mt5_signals)} signal records")

    print(f"\nLoading config from: {args.config}")
    app_settings = load_settings(args.config)
    boll_settings = app_settings.strategy.boll_mr

    # Convert to params
    params = BollMeanReversionParams(
        logic_mode=boll_settings.logic_mode,
        entry_mode=boll_settings.entry_mode,
        allowed_start_hour=boll_settings.allowed_start_hour,
        allowed_end_hour=boll_settings.allowed_end_hour,
        time_offset_hours=boll_settings.time_offset_hours,
        boll_period=boll_settings.boll_period,
        boll_dev=boll_settings.boll_dev,
        atr_period=boll_settings.atr_period,
        atr_vol_limit=boll_settings.atr_vol_limit,
        rsi_period=boll_settings.rsi_period,
        rsi_overbought=boll_settings.rsi_overbought,
        rsi_oversold=boll_settings.rsi_oversold,
        shortest_closing_time=boll_settings.shortest_closing_time,
        struct_atr_sl=boll_settings.struct_atr_sl,
        vol_atr_sl=boll_settings.vol_atr_sl,
        bool_mid_atr_tp=boll_settings.mid_atr_tp,
        bool_mid_atr_tp2=boll_settings.mid_atr_tp2,
        bool_uplow_atr_tp=boll_settings.uplow_atr_tp,
        ma_period=boll_settings.ma_period,
        gap_cooldown_bars=boll_settings.gap_cooldown_bars,
        gap_threshold_multiplier=boll_settings.gap_threshold_multiplier,
        point=app_settings.broker.point,
    )

    # Override logic mode if specified
    if args.logic_mode:
        params.logic_mode = args.logic_mode

    print(f"  Logic mode: {params.logic_mode}")
    print(f"  Entry mode: {params.entry_mode}")
    print(f"  Time filter: {params.allowed_start_hour}:00 - {params.allowed_end_hour}:00 (offset: {params.time_offset_hours})")

    print(f"\nRunning Python strategy...")
    strategy = BollMeanReversionStrategy(params)
    py_signals = strategy.generate_signals(ohlcv_df, diagnose=True)

    print(f"  Python diagnostics: {strategy.last_diagnostics}")

    # Compare
    results = compare_signals(mt5_signals, strategy.last_signal_events, strategy.last_signal_state)
    print_report(results)

    # Return success if match rate is high
    if results["match_rate"] >= 99.0 and results["mismatch_count"] <= 5:
        print("\n[OK] Signals are well aligned!")
        return 0
    else:
        print("\n[!] Signal alignment needs review")
        return 1


if __name__ == "__main__":
    sys.exit(main())
